version: '3.4'

services:
  frontend:
    image: frontend:latest
    environment:
      - PORT=80
    ports:
      - 8080:80
  backend:
    image: backend:latest
    # environment: #secrets and environment variables here
    ports:
      - 3000:3000
    networks:
      - aime

networks:
  aime: