version: '3.4'

services:
  frontend:
    image: ninipriv/aime:frontend_0.1_4691339334
    environment:
      - PORT=3000
      - PUBLIC_BACKEND_URL=${PUBLIC_BACKEND_URL}
      # - PUBLIC_BACKEND_URL=https://167.99.130.48/api
      # - PUBLIC_BACKEND_URL=https://localhost/api
    ports:
      - 8080:3000
    networks:
      - proach_aime
  backend:
    image: ninipriv/aime:backend_0.1_4692817675
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3    
    networks:
      - proach_aime
  nginx:
    image: nginx:stable
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    networks:
      - proach_aime
    depends_on:
      backend:
        condition: service_healthy
      

networks:
  proach_aime: 
