version: '3.4'

services:
  proach:
    image: proach
    build:
      context: proach
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
