version: '3.4'

services:
  frontend:
    image: frontend:latest
    environment:
      - PORT=3000
    ports:
      - 8080:3000
  backend:
    image: backend:latest
    ports:
      - 3000:3000
    networks:
      - aime

networks:
  aime: