name: Build and Push Backend Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - backend/**

env:
  DOCKER_REPOSITORY: ninipriv/aime
  IMAGE_NAME: backend
  IMAGE_VERSION: 0.1
  CONTEXT_SUBDIR: backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: "${{ github.server_url }}/${{ github.repository }}.git#${{ github.ref }}:${{ env.CONTEXT_SUBDIR }}"
        # context: "{{defaultContext}}:backend"
        # context: ./backend
        # file: ./backend/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_NAME }}_${{ env.IMAGE_VERSION }}_${{ github.run_id }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.CLASSIC_AUTH_TOKEN }}